# Generated by Django 5.2.4 on 2025-07-22 17:35

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_slug_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت\u200cنام'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, null=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
