# Generated by Django 5.2.4 on 2025-07-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_massemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='فایل')),
                ('is_minified', models.BooleanField(default=False, verbose_name='مینیفای')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'فایل رسانه\u200cای',
                'verbose_name_plural': 'فایل\u200cهای رسانه\u200cای',
            },
        ),
        migrations.AlterModelOptions(
            name='massemail',
            options={'verbose_name': ' ایمیل', 'verbose_name_plural': 'ایمیل '},
        ),
        migrations.AlterField(
            model_name='massemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='massemail',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
