# Generated by Django 5.2.4 on 2025-07-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_mediafile_alter_massemail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={},
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='file',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_name',
            field=models.CharField(default='', max_length=255, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='is_minified',
            field=models.BooleanField(default=False, verbose_name='مینیفای '),
        ),
    ]
