# Generated by Django 5.2.4 on 2025-07-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_mediafile_options_remove_mediafile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file_name',
            field=models.FileField(upload_to='uploads/', verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='is_minified',
            field=models.BooleanField(default=False, verbose_name='مینیفای'),
        ),
    ]
