# Generated by Django 5.2.4 on 2025-07-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_mediafile_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='file_name',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file',
            field=models.FileField(default='uploads/default_placeholder.txt', upload_to='uploads/', verbose_name='نام فایل'),
        ),
    ]
