# Generated by Django 5.2.4 on 2025-07-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_mediafile_file_name_mediafile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'فایل', 'verbose_name_plural': 'فایل\u200cها'},
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='نام فایل'),
        ),
    ]
