# Generated by Django 5.2.4 on 2025-07-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_mediafile_options_alter_mediafile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
