# Generated by Django 5.2.4 on 2025-08-02 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربرها '},
        ),
    ]
