# Generated by Django 5.2.4 on 2025-08-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('level', models.CharField(default='info', max_length=20, verbose_name='سطح')),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن سیستم',
                'verbose_name_plural': 'نوتیفیکیشن\u200cهای سیستم',
                'ordering': ['-timestamp'],
            },
        ),
    ]
